// react/src/components/Message.jsx
import {
  useEffect,
  useState,
} from "react";

export default function  Message({ onCustomChange }) {
  const [ message, setMessage ] = useState('Hello world');

  useEffect(() => {
    console.log('Message updated', message);
    onCustomChange(message);
  }, [message]);

  return (
    <div>
      <p>{message}</p>
      <input type="text" value={message} onChange={(e) => setMessage(e.target.value)} />
    </div>
  );
}

// vue/src/components/Message.vue
<script setup>
import {
  ref,
  watch,
} from 'vue';

const emit = defineEmits(['update:message']);
const message = ref('Hello world');

(() => {
  emit('update:message', message.value);
})();

watch(message, (newValue) => {
  console.log('Message updated', newValue);
  emit('update:message', newValue);
});
</script>

<template>
  <div>
    <p>{{ message }}</p>
    <input v-model="message" />
  </div>
</template>
